# Default values for rancher-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: yankcrime/rancher-demo
  tag: 3c44add
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

app:
  localization:
    title: "Rancher Demo App"
    pets: "cows" # available pets include 'cows' and 'chameleons' and possibly 'cowmeleons'
    color: "black" # container background color (any color name from the CSS pallete)

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  tls: False
  annotations: {}
  paths: []
  host:

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
