helm:
  chart: ./charts/rancher-demo/v0.1.0
  values:
    replicaCount: 3
    app:
      localization:
        title: "Rancher Demo App, powered by Fleet"
        pets: "cowmeleons"
        color: "pink"
    ingress:
      enabled: false
      tls: False
      host: rancher-demo.192.168.20.165.dnsify.me
